openapi: 3.0.3
info:
  title: Identity-as-Code API
  version: 0.1.0
  description: Identity and vCluster provisioning API with GitOps commit and Helm-based provisioner integration.
components:
  schemas:
    IdentityAsCodeRequest:
      type: object
      required: [department, team, user, vcluster]
      properties:
        department:
          type: string
        team:
          type: string
        user:
          type: object
          required: [username, email]
          properties:
            username:
              type: string
            email:
              type: string
        vcluster:
          type: object
          required: [name, cpu, memory, disk, network]
          properties:
            name:
              type: string
            cpu:
              type: string
            memory:
              type: string
            disk:
              type: string
            network:
              type: string
paths:
  /health:
    get:
      summary: Health check
      responses:
        "200":
          description: Service health
  /config:
    get:
      summary: Get effective integration and provisioner config
      responses:
        "200":
          description: Current integration config view
  /render:
    post:
      summary: Render TeamWorkspace manifest from request payload
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IdentityAsCodeRequest"
      responses:
        "200":
          description: Manifest rendered
        "400":
          description: Invalid request payload
  /apply:
    post:
      summary: Commit IaC manifest and trigger vCluster provisioner
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/IdentityAsCodeRequest"
      responses:
        "200":
          description: Applied and committed
        "400":
          description: Invalid request payload
        "500":
          description: GitOps or provisioner apply failed
