kind: Backstage
apiVersion: rhdh.redhat.com/v1alpha4
metadata:
  name: rhdh
spec:
  application:
    imagePullSecrets:
      - "rh-pull-secret"
    route:
      enabled: false
    image: "quay.io/$QUAY_REPO:$TAG_NAME"
    appConfig:
      configMaps:
        - name: app-config-rhdh
        - name: dynamic-plugins-config
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: dynamic-plugins
    # Increase ephemeral storage limit for dynamic plugins installation
    # This prevents "No space left on device" errors during plugin extraction
    replicas: 1
    podSpec:
      initContainers:
        - name: install-dynamic-plugins
          resources:
            requests:
              cpu: 250m
              memory: 256Mi
            limits:
              cpu: 1000m
              memory: 2.5Gi
              ephemeral-storage: 10Gi # Increased from default 5Gi
    extraEnvs:
      envs:
        - name: NODE_OPTIONS
          value: "--no-node-snapshot"
      secrets:
        - name: rhdh-secrets
        - name: redis-secret
