kind: Backstage
apiVersion: rhdh.redhat.com/v1alpha4
metadata:
  name: rhdh
spec:
  application:
    appConfig:
      configMaps:
        - name: app-config-rhdh
      mountPath: /opt/app-root/src
    dynamicPluginsConfigMapName: dynamic-plugins
    extraEnvs:
      envs:
        - name: NODE_OPTIONS
          value: "--no-node-snapshot"
      secrets:
        - name: rhdh-secrets
    extraFiles:
      configMaps:
        - name: rbac-policy
      mountPath: /opt/app-root/src/rbac
