import { alpha, Theme } from '@mui/material/styles';

export const getOpsPilotStyles = (theme: Theme) => {
  const divider = theme.palette.divider;
  const bgDefault = theme.palette.background.default;
  const bgPaper = theme.palette.background.paper;
  const textPrimary = theme.palette.text.primary;
  const textSecondary = theme.palette.text.secondary;
  const primary = theme.palette.primary.main;
  const success = theme.palette.success.main;
  const warning = theme.palette.warning.main;
  const error = theme.palette.error.main;
  const info = theme.palette.info.main;

  return {
    root: {
      display: 'flex',
      height: '100vh',
      bgcolor: bgDefault,
      color: textPrimary,
    },
    sidebar: {
      width: 64,
      bgcolor: bgPaper,
      borderRight: `1px solid ${divider}`,
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      py: 3,
      gap: 2,
    },
    sidebarBadge: {
      width: 40,
      height: 40,
      borderRadius: 2,
      background: `linear-gradient(135deg, ${primary}, ${info})`,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      boxShadow: `0 8px 24px ${alpha(primary, 0.35)}`,
    },
    sidebarDivider: {
      width: '60%',
      borderColor: divider,
    },
    sidebarMenu: {
      display: 'flex',
      flexDirection: 'column',
      gap: 1,
    },
    main: {
      '--ops-chat-width': 'clamp(360px, 34vw, 520px)',
      display: 'flex',
      flex: 1,
      marginLeft: { xs: 0, lg: '76px' },
      width: { xs: '100%', lg: 'calc(100% - 76px)' },
      maxWidth: { xs: '100%', lg: 'calc(100% - 76px)' },
      minWidth: 0,
      flexDirection: { xs: 'column', lg: 'row' },
      overflow: 'hidden',
      boxSizing: 'border-box',
    },
    chatPanel: {
      width: { xs: '100%', lg: 'var(--ops-chat-width)' },
      minWidth: { xs: 0, lg: 360 },
      maxWidth: '100%',
      flex: { xs: '1 1 auto', lg: '0 0 var(--ops-chat-width)' },
      boxSizing: 'border-box',
      borderRight: `1px solid ${divider}`,
      borderBottom: { xs: `1px solid ${divider}`, lg: 'none' },
      bgcolor: bgPaper,
      display: 'flex',
      flexDirection: 'column',
      minHeight: { xs: 320, lg: 0 },
    },
    chatHeader: {
      px: 3,
      py: 2,
      borderBottom: `1px solid ${divider}`,
      display: 'flex',
      justifyContent: 'space-between',
    },
    chatHeaderTitle: {
      fontWeight: 600,
      color: textPrimary,
      display: 'flex',
      alignItems: 'center',
      gap: 1,
    },
    chatStatusDot: {
      width: 8,
      height: 8,
      borderRadius: '50%',
      bgcolor: success,
      boxShadow: `0 0 8px ${alpha(success, 0.7)}`,
    },
    chatBody: {
      flex: 1,
      overflowY: 'auto',
      px: { xs: 2, md: 3 },
      py: 3,
      display: 'flex',
      flexDirection: 'column',
      gap: 3,
    },
    messageAvatar: (isAi: boolean) => ({
      width: 32,
      height: 32,
      minWidth: 32,
      minHeight: 32,
      flexShrink: 0,
      borderRadius: '50%',
      bgcolor: isAi ? info : alpha(textSecondary, 0.3),
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    }),
    messageBubble: (isUser: boolean) => ({
      bgcolor: isUser ? primary : bgDefault,
      color: isUser ? theme.palette.common.white : textPrimary,
      border: isUser ? 'none' : `1px solid ${divider}`,
      px: 2,
      py: 1.5,
      borderRadius: 2,
      borderTopRightRadius: isUser ? 0 : 8,
      borderTopLeftRadius: isUser ? 8 : 0,
    }),
    chatFooter: {
      px: { xs: 2, md: 3 },
      py: 2,
      borderTop: `1px solid ${divider}`,
      bgcolor: bgPaper,
    },
    canvas: {
      flex: 1,
      width: { xs: '100%', lg: 'calc(100% - var(--ops-chat-width))' },
      maxWidth: { xs: '100%', lg: 'calc(100% - var(--ops-chat-width))' },
      display: 'flex',
      flexDirection: 'column',
      minWidth: 0,
      boxSizing: 'border-box',
    },
    canvasHeader: {
      height: 56,
      borderBottom: `1px solid ${divider}`,
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
      px: 3,
      bgcolor: bgDefault,
    },
    systemChip: {
      display: 'flex',
      alignItems: 'center',
      gap: 1,
      px: 2,
      py: 0.5,
      borderRadius: 999,
      border: `1px solid ${divider}`,
      bgcolor: bgPaper,
    },
    canvasBody: {
      flex: 1,
      overflowY: 'auto',
      px: { xs: 2, md: 4 },
      py: 4,
      bgcolor: bgDefault,
      backgroundImage: "url('/noise.svg')",
      backgroundRepeat: 'repeat',
      backgroundSize: '200px 200px',
    },
    emptyState: {
      display: 'flex',
      flexDirection: 'column',
      alignItems: 'center',
      textAlign: 'center',
      gap: 3,
      minHeight: '65vh',
      justifyContent: 'center',
    },
    emptyBadge: {
      width: 88,
      height: 88,
      borderRadius: 3,
      bgcolor: bgPaper,
      border: `1px solid ${divider}`,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      boxShadow: `0 24px 48px ${alpha(bgDefault, 0.6)}`,
    },
    sectionCard: {
      bgcolor: bgPaper,
      border: `1px solid ${divider}`,
      borderRadius: 2,
    },
    clusterHeader: {
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    clusterTitle: {
      display: 'flex',
      gap: 1,
      fontWeight: 700,
      color: theme.palette.common.white,
    },
    clusterMeta: {
      mt: 0.5,
      color: textSecondary,
      fontSize: 12,
    },
    topoCard: {
      bgcolor: bgPaper,
      border: `1px solid ${divider}`,
      borderRadius: 2,
      p: 3,
    },
    topoRow: {
      display: 'flex',
      gap: 4,
      justifyContent: 'center',
      alignItems: 'center',
      position: 'relative',
      py: 3,
      '&::before': {
        content: '""',
        position: 'absolute',
        left: 32,
        right: 32,
        top: '50%',
        height: 2,
        bgcolor: alpha(textSecondary, 0.25),
        zIndex: 0,
      },
    },
    topoNode: (color: string) => ({
      width: 56,
      height: 56,
      borderRadius: 2,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
      border: `2px solid ${alpha(color, 0.5)}`,
      bgcolor: bgDefault,
      boxShadow: `0 0 20px ${alpha(color, 0.25)}`,
      position: 'relative',
    }),
    topoBadge: {
      position: 'absolute',
      top: -6,
      right: -6,
      width: 20,
      height: 20,
      borderRadius: '50%',
      bgcolor: bgPaper,
      border: `1px solid ${divider}`,
      color: textPrimary,
      fontSize: 10,
      display: 'flex',
      alignItems: 'center',
      justifyContent: 'center',
    },
    tableHeaderRow: {
      display: 'grid',
      gridTemplateColumns: '2fr 1fr 1fr 1fr 1fr',
      bgcolor: alpha(textSecondary, 0.15),
      px: 3,
      py: 1.5,
    },
    tableHeaderCell: {
      color: textPrimary,
      fontSize: 12,
      fontWeight: 600,
    },
    tableMono: {
      color: textPrimary,
      fontFamily: 'monospace',
      fontSize: 12,
    },
    tableRole: {
      color: textSecondary,
      fontSize: 12,
      textTransform: 'uppercase',
    },
    statusReady: {
      color: success,
      fontSize: 12,
    },
    statusNotReady: {
      color: error,
      fontSize: 12,
    },
    progressTrack: {
      width: 64,
      height: 6,
      bgcolor: alpha(textSecondary, 0.2),
      borderRadius: 8,
      overflow: 'hidden',
    },
    progressCpu: {
      height: '100%',
      bgcolor: primary,
    },
    progressMemory: {
      height: '100%',
      bgcolor: theme.palette.secondary.main,
    },
    topoLegend: {
      display: 'flex',
      gap: 2,
      color: textSecondary,
      fontSize: 12,
    },
    legendDotControl: {
      width: 8,
      height: 8,
      borderRadius: '50%',
      bgcolor: info,
    },
    legendDotWorker: {
      width: 8,
      height: 8,
      borderRadius: '50%',
      bgcolor: success,
    },
    legendDotIssue: {
      width: 8,
      height: 8,
      borderRadius: '50%',
      bgcolor: error,
    },
    nodeName: {
      fontSize: 12,
      color: textPrimary,
      mt: 1,
    },
    nodeStatus: (ready: boolean) => ({
      fontSize: 10,
      color: ready ? success : error,
    }),
    nodeRow: {
      display: 'grid',
      gridTemplateColumns: '2fr 1fr 1fr 1fr 1fr',
      px: 3,
      py: 1.5,
      borderTop: `1px solid ${divider}`,
      '&:hover': { bgcolor: bgDefault },
    },
    pipelineCard: (isFailed: boolean) => ({
      bgcolor: bgPaper,
      borderRadius: 2,
      border: `1px solid ${isFailed ? alpha(error, 0.6) : divider}`,
      px: 2,
      py: 2,
      cursor: 'pointer',
      '&:hover': { borderColor: alpha(info, 0.7) },
    }),
    pipelineTitle: {
      color: textPrimary,
      fontWeight: 600,
    },
    pipelineMeta: {
      fontSize: 12,
      color: textSecondary,
    },
    logsPanel: {
      bgcolor: bgPaper,
      borderRadius: 2,
      border: `1px solid ${divider}`,
      overflow: 'hidden',
    },
    logsHeader: {
      px: 2,
      py: 1.5,
      borderBottom: `1px solid ${divider}`,
      bgcolor: bgDefault,
      display: 'flex',
      justifyContent: 'space-between',
      alignItems: 'center',
    },
    logsHeaderText: {
      fontFamily: 'monospace',
      fontSize: 12,
      color: textPrimary,
    },
    logsBody: {
      px: 2,
      py: 2,
      bgcolor: bgDefault,
      height: 360,
      overflow: 'auto',
    },
    approvalCard: {
      mt: 1,
      p: 2,
      border: `1px solid ${divider}`,
      borderRadius: 2,
      bgcolor: bgPaper,
      width: '100%',
    },
    approvalTitle: {
      fontWeight: 600,
      color: textPrimary,
    },
    approvalSubtitle: {
      fontSize: 12,
      color: textSecondary,
    },
    approvalChip: (approved: boolean) => ({
      bgcolor: approved ? alpha(success, 0.2) : alpha(textSecondary, 0.2),
      color: approved ? success : textSecondary,
    }),
    successChip: {
      bgcolor: alpha(success, 0.15),
      color: success,
      border: `1px solid ${alpha(success, 0.35)}`,
    },
    statusDot: {
      width: 8,
      height: 8,
      borderRadius: '50%',
      bgcolor: success,
    },
    messageTimestamp: {
      fontSize: 10,
      color: textSecondary,
      mt: 0.5,
    },
    headerCrumb: {
      fontSize: 13,
      color: textSecondary,
    },
    headerCrumbActive: {
      color: textPrimary,
      fontWeight: 600,
    },
    emptySubtitle: {
      color: textSecondary,
      mt: 1,
      maxWidth: 520,
    },
    emptyActionButton: {
      textAlign: 'left',
      bgcolor: bgPaper,
      border: `1px solid ${divider}`,
      color: textPrimary,
      px: 3,
      py: 2,
      borderRadius: 2,
      justifyContent: 'flex-start',
      gap: 2,
      '&:hover': { bgcolor: bgDefault },
    },
    cardSubtitle: {
      fontSize: 12,
      color: textSecondary,
    },
    sidebarIcon: (active: boolean) => ({
      color: active ? theme.palette.common.white : textSecondary,
      bgcolor: active ? primary : 'transparent',
      '&:hover': {
        bgcolor: active ? theme.palette.primary.dark : alpha(textSecondary, 0.2),
        color: textPrimary,
      },
    }),
    navButton: {
      mt: 1,
      alignSelf: 'flex-start',
      borderColor: divider,
      color: textPrimary,
    },
    suggestionChip: {
      bgcolor: bgPaper,
      border: `1px solid ${divider}`,
      color: textPrimary,
      textTransform: 'none',
      '&:hover': { bgcolor: bgDefault },
    },
    inputArea: {
      width: '100%',
      borderRadius: 12,
      border: `1px solid ${divider}`,
      background: bgDefault,
      color: textPrimary,
      padding: '12px 48px 12px 12px',
      minHeight: 56,
      resize: 'none',
    },
    inputButton: {
      position: 'absolute',
      right: 8,
      top: 8,
      bgcolor: primary,
      color: theme.palette.common.white,
      '&:hover': { bgcolor: theme.palette.primary.dark },
    },
    headerButton: {
      color: textSecondary,
    },
    iconSuccess: { color: success, fontSize: 16 },
    iconWarning: { color: warning, fontSize: 16 },
    iconError: { color: error, fontSize: 16 },
    iconInfo: { color: info, fontSize: 16 },
    textSecondary: { color: textSecondary },
  };
};
